OrdererOrgs:
  - Name: Orderer
    Domain: permit.com
    EnableNodeOUs: true
    CA:
      Country: US
      Province: California
      Locality: San Francisco
      OrganizationalUnit: Hyperledger Fabric
      StreetAddress: address for org
      PostalCode: 94105
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - 127.0.0.1
    Users:
      Count: 1 