version: '3.8'

services:
  nfpa-backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - nfpa-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nfpa_permits
      POSTGRES_USER: nfpa_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nfpa-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nfpa-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nfpa-backend
    networks:
      - nfpa-network

volumes:
  postgres_data:
  redis_data:

networks:
  nfpa-network:
    driver: bridge
